### ISSUE TITLE
Cleaner approach to init-parking-spaces

### ISSUE THREAD

**Issue by smnplk** [anthonygalea/garage-simulation#1]
Hi! 

Thanks for great example of using Refs. I would just make init-parking-spaces function a bit less noisy. 

```
(defn init-parking-spaces
  "parking-spaces is a map like {0 3 1 5}"
  [parking-spaces]
  (into #{}
        (for [[level spaces] parking-spaces space-number (range 1 (inc spaces))]
          [level space-number])))
```

**Comment by anthonygalea** [comment]
Hi,
In a subsequent post I had switched from a map to a vector.
See http://www.anthony-galea.com/blog/post/hello-parking-garage-meet-clojure.spec
However I think your suggestion still applies:

``` clojure
(for [[level spaces] (map-indexed vector parking-spaces)
      space-number (range spaces)]
  [level space-number])
```

Thanks for your feedback!
